services:
  - type: web
    name: registro-alumnos-web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: registro-alumnos-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: registro-alumnos-db
    databaseName: registro_alumnos
    user: registro_user
    plan: free

    